### ISSUE TITLE
Marzban Sub

### ISSUE THREAD

**Issue by ShahabShadovv** [wizwizdev/wizwizdev#3]
Salam Lotfan Panel Marzban Ham Okay Konid Ke Subscriptione Marzban Bede Be Moshtari 

Ty <3

**Comment by wizwizdev** [comment]
سلام مرزبان اضافه نمیشه و حتی خودش ربات داره

**Comment by ExPLoSiVe1988** [comment]
سلام خسته نباشید
ببینم وب پنل ویز‌ویز رو بعد از نصب کپی نکردم
از کجا میتونم لینک وب پنل رو بردارم که بتونم وارد بشم
خیلی ممنون از زحمات شما
